### ISSUE TITLE
Error while running uatg

### ISSUE THREAD

**Issue by snehashri04** [incoresemi/uatg#6]
Traceback (most recent call last):
  File "/home/sneha/.local/bin/uatg", line 11, in <module>
    load_entry_point('uatg', 'console_scripts', 'uatg')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sneha/uatg/uatg/main.py", line 246, in from_config
    generate_sv(work_dir=config['uatg']['work_dir'],
  File "/home/sneha/uatg/uatg/test_generator.py", line 227, in generate_sv
    _sv = plugin.plugin_object.generate_covergroups(alias_dict)
  File "/home/sneha/myquickstart/chromite_uatg_tests/modules/branch_predictor/uatg_gshare_fa_mispredict_loop_01.py", line 109, in generate_covergroups
    mispredict_flag = config['branch_predictor']['wire']['bpu_mispredict_flag']
KeyError: 'branch_predictor'

I get the following bug while running uatg, the aliasing.yaml created during "uatg setup" should have the node as "branch_predictor" not "bpu" https://github.com/incoresemi/uatg/blob/main/uatg/utils.py#L427

**Comment by neelgala** [comment]
what are the steps to replicate the bug ?

**Comment by snehashri04** [comment]
1. Cloned the https://github.com/incoresemi/chromite_uatg_tests repo in /myquickstart directory
2. Ran the 'uatg setup' after installing the package
3. Consequently ran the 'from-config' command where I got the bug
Basically followed this https://uatg.readthedocs.io/en/latest/installation.html#running-uatg step-by-step

**Comment by Alenkruth** [comment]
@snehashri04 
1. I am fixing this issue in utils.py now and will be merged to master.
2. On a side note, The *aliasing.yaml* as well as the *dut_config.yaml* are just template files for the user to get started with creating those YAML files which are required for UATG. It is better if you use [this](https://github.com/incoresemi/chromite_uatg_tests/blob/main/aliasing.yaml) YAML file, as it is the one that will be updated with every new test we write. 

Thanks.

**Comment by snehashri04** [comment]
Okay thanks @Alenkruth

**Comment by Alenkruth** [comment]
The issue has been fixed in [this](https://github.com/incoresemi/uatg/pull/4) merge. I am closing the issue.
