### ISSUE TITLE
Bug while running chromite-uatg-tests

### ISSUE THREAD

**Issue by snehashri08** [incoresemi/uatg#7]
While running "uatg from-config -c config.ini -v debug" with the latest commits in uatg and chromite-uatg-tests, I got this error

Traceback (most recent call last):
  File "/home/sneha/.local/bin/uatg", line 11, in <module>
    load_entry_point('uatg', 'console_scripts', 'uatg')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in _call_
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sneha/uatg/uatg/main.py", line 236, in from_config
    generate_tests(work_dir=config['uatg']['work_dir'],
  File "/home/sneha/uatg/uatg/test_generator.py", line 110, in generate_tests
    asm_body = plugin.plugin_object.generate_asm()
  File "/home/sneha/myquickstart/chromite_uatg_tests/modules/decoder/uatg_decoder_arithmetic_insts.py", line 39, in generate_asm
    for inst in arithmetic_instructions['add-sub-reg']:
KeyError: 'add-sub-reg'

**Comment by purushothaman-p** [comment]
Solved the issue in chromite_uatg_tests repository in the dev-branch. Checkout the dev branch to resolve this issue immediately. The issue can be closed once dev is merged with main or by the next feature release.
